;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        beginning-of-visual-line
        end-of-visual-line
        evil-backward-char
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-insert-line
        evil-normal-state
        orgonomic-delete-backward-char
        orgonomic-minus
        ))

(setq mc/cmds-to-run-once
      '(
        org-self-insert-command
        ))
